# Generated by Django 6.0.5 on 2026-05-19 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progress',
            name='progress_percent',
            field=models.IntegerField(default=0),
        ),
    ]
