# Generated by Django 4.2.30 on 2026-05-20 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_usercontentstatus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marks',
            name='exercise_id',
        ),
        migrations.RemoveField(
            model_name='marks',
            name='lecture_id',
        ),
        migrations.RemoveField(
            model_name='marks',
            name='quiz_id',
        ),
        migrations.AddField(
            model_name='users',
            name='bio',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='avatar',
            field=models.FileField(blank=True, null=True, upload_to='avatars/'),
        ),
        migrations.DeleteModel(
            name='Gradebook',
        ),
        migrations.DeleteModel(
            name='Marks',
        ),
    ]
