# Generated by Django 4.2.30 on 2026-05-20 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_remove_marks_exercise_id_remove_marks_lecture_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comments',
        ),
    ]
